const ActionTypes = {
  GET_DEPARTMENT_RESPONSE: "GET_DEPARTMENT_RESPONSE",
  GET_DEPARTMENT: "GET_DEPARTMENT",
  CREATE_DEPARTMENT: "CREATE_DEPARTMENT",
  CREATE_DEPARTMENT_RESPONSE: "CREATE_DEPARTMENT_RESPONSE",
  DELETE_DEPARTMENT: "DELETE_DEPARTMENT",
  DELETE_DEPARTMENT_RESPONSE: "DELETE_DEPARTMENT_RESPONSE",
};
export default ActionTypes;
